function roiTable = readEBRoiFiles(filename)
%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Users\Zhongxu\Documents\myStudy\Faces_Repetiion_fMRI\Programming_ExptBuilder\Faces_block1_fMRI_10cb\library\interestAreaSet\F1.jpg.ias
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2015/11/21 12:59:32

%% Initialize variables.
if nargin < 1
    disp('no input file is defined, automatically readin F1 file in Faces_Repetiion_fMRI\Programming_ExptBuilder\Faces_block1_fMRI_10cb\library\interestAreaSet\F1.jpg.ias');
filename = 'C:\Users\Zhongxu\Documents\myStudy\Faces_Repetiion_fMRI\Programming_ExptBuilder\Faces_block1_fMRI_10cb\library\interestAreaSet\F1.jpg.ias';
end

delimiter = '\t';
startRow = 2;

%% Format string for each line of text:
%   column1: text (%s)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: text (%s)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%f%f%f%f%f%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'HeaderLines' ,startRow-1, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
roiTable = table(dataArray{1:end-1}, 'VariableNames', {'shape','n','x1','y1','x2','y2','roiName'});
%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;